## REVISÃO NUMPY


In [14]:
import numpy as np

# Array 1D a partir de um vetor
arr1d = np.array([1, 2, 3, 4])

# Array 2D a partir de uma matriz
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Array 3D a partir de um tensor
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [15]:
arr1d

array([1, 2, 3, 4])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:


a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


### Funções úteis

In [20]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.86234947 0.04658657]
 [0.46023115 0.45670944]]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3)
print(arr.ndim)    # 2
print(arr.dtype)   # int64 (depende do sistema)
print(arr.size)    # 6

(2, 3)
2
int64
6


### Indexação e Slicing



In [26]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],
              [5,6,7,8], 
              [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] #Lembre se, inicia-se em 0 e o valor após os ":" não é incluso, ou seja, é n-1.
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(f"Aparecendo o 2 com um array simples {a[0, 1]}")   # Prints "2"
print(f"Aparecendo o conjunto selecionado {b}")
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

Aparecendo o 2 com um array simples 2
Aparecendo o conjunto selecionado [[2 3]
 [6 7]]
77


In [23]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [30]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]" #Podemos acessar os itens passando listas de index de linhas e colunas

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

#Também possivel acessar o mesmo item 
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]


In [31]:
#FUNÇÃO DE ITERAÇÃO COM LISTAS DE INDEXES

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1]) 

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

#Neste caso, o primeiro item é na linha 0 e coluna 0. 
#Depois, as linhas andam 4, sem contar a ultima que foi lida. Sendo na segunda iteração as linhas: 1 -> 2 -> 3 -> 0, logo a próxima linha lida é a 1, e coluna 2.
#Depois, linhas : 2 -> 3 -> 0 - > 1, logo a proxima linha lida é a 2, coluna 0.
# e assim por diante.

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [32]:
#USANDO BOOLEANOS
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## DATATYPES


In [33]:

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)       

int64
float64
int64


## OPERAÇÕES MATEMÁTICAS



In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5, 7, 9] SOMA  np.add(x, y)
print(a * 2)  # [2, 4, 6] MULTIPLICAÇÃO  np.multiply(x, y) elemento a elemento
print(a @ b) # Multiplicação matricial (produto escalar)
print(a - b) # np.subtract(x, y)
print(a / b) #np.divide(x, y)
print(np.sqrt(a))  # [1.0, 1.414, 1.732] RAIZ QUADRADA

[5 7 9]
[2 4 6]
32
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]


In [38]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## FUNÇÕES DE AGREGAÇÃO

In [39]:
arr = np.array([[1, 2], [3, 4]])

print(arr.sum())      # 10
print(arr.max())      # 4
print(arr.mean())     # 2.5
print(arr.std())      # Desvio padrão
print(arr.sum(axis=0))  # Soma das colunas: [4, 6]

10
4
2.5
1.118033988749895
[4 6]


### Transpondo uma matriz
Em matemática, matriz transposta é a matriz que se obtém da troca de linhas por colunas de uma dada matriz

In [40]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

print(a + b)  # [[11, 22], [13, 24]]

[[11 22]
 [13 24]]


In [42]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Exemplo acima é lento ! Podemos fazer de uma maneira diferente.

In [43]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Redimensionamento

In [45]:
arr = np.arange(6)  # [0, 1, 2, 3, 4, 5]
print(arr)
# Transformar em 2x3
arr_2d = arr.reshape(2, 3)
print(arr_2d)
# Achatar para 1D
arr_flat = arr_2d.flatten()
print(arr_flat)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
